kind: pipeline
type: docker
name: Testing Python CI/CD


steps:
- name: Tests
  image: python
  commands:
  - pip3 install -r requirements.txt
  - pytest
- name: Install and deploy
  image: python
  environment:
    MY_PASS:
      from_secret: MY_PASS
  commands:
  - pip3 install -r requirements.txt
  - python3 main.py

trigger:
  branch:
    exclude:
    - master
